remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Traffic accident analysis in New York City, January-August 2020 by Shutong Ji and Henian Wu
description: Final App
show_downloads: ['true']