remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
description: Final App by Shutong Ji and Henian Wu (team 29)
show_downloads: ['true']